## source ./setDomainEnv.sh
##java weblogic.WLST /yourpath/Publicationqueue.py
connect('weblogic','weblogic1','t3://localhost:7001')
## Creating a JMS Server (name = PublicationJMSServer)
edit()
startEdit()
cd('/')
print 'Creating JMS Server.'
cmo.createJMSServer('PublicationJMSServer')
cd('/JMSServers/PublicationJMSServer')
cmo.addTarget(getMBean('/Servers/AdminServer'))
activate()

## Creating a Module (name = PubJMSSystemResource) in AdminServer 

edit()
startEdit()
cd('/')
cmo.createJMSSystemResource('PubJMSSystemResource')
cd('/JMSSystemResources/PubJMSSystemResource')
cmo.addTarget(getMBean('/Servers/AdminServer'))
cmo.createSubDeployment('pubsub')
activate()

#Create a Queue ( name = PubQueue)

edit()
startEdit()
cd('/')
cd('/JMSSystemResources/PubJMSSystemResource/JMSResource/PubJMSSystemResource')
cmo.createQueue('PubQueue')
cd('/')
cd('/JMSSystemResources/PubJMSSystemResource/JMSResource/PubJMSSystemResource/Queues/PubQueue')
set('JNDIName','PubQueue')
set('SubDeploymentName','pubsub')
cd('/')
cd('/JMSSystemResources/PubJMSSystemResource/SubDeployments/pubsub')
set('Targets',jarray.array([ObjectName('com.bea:Name=PublicationJMSServer,Type=JMSServer')],ObjectName))
activate()


#Create error Queue ( name = PubErrorQueue, JMSSystemResource0, subdeployment0 )
edit()
startEdit()
cd('/')
cd('/JMSSystemResources/PubJMSSystemResource/JMSResource/PubJMSSystemResource')
cmo.createQueue('PubErrorQueue')
cd('/')
cd('/JMSSystemResources/PubJMSSystemResource/JMSResource/PubJMSSystemResource/Queues/PubErrorQueue')
set('JNDIName','PubErrorQueue')
set('SubDeploymentName','pubsub')
cd('/')
cd('/JMSSystemResources/PubJMSSystemResource/SubDeployments/pubsub')
set('Targets',jarray.array([ObjectName('com.bea:Name=PublicationJMSServer,Type=JMSServer')],ObjectName))
activate()

##Create a connection Factory ( name = PubConnectionFactory)

edit()
startEdit()
cd('/JMSSystemResources/PubJMSSystemResource/JMSResource/PubJMSSystemResource')
cmo.createConnectionFactory('PubConnectionFactory')
cd('/')
cd('/JMSSystemResources/PubJMSSystemResource/JMSResource/PubJMSSystemResource/ConnectionFactories/PubConnectionFactory')
set('JNDIName','PubConnectionFactory')
cd('/')
cd('/JMSSystemResources/PubJMSSystemResource/JMSResource/PubJMSSystemResource/ConnectionFactories/PubConnectionFactory/SecurityParams/PubConnectionFactory')
set('AttachJMSXUserId','false')
cd('/')
cd('/JMSSystemResources/PubJMSSystemResource/JMSResource/PubJMSSystemResource/ConnectionFactories/PubConnectionFactory')
set('SubDeploymentName','pubsub')
cd('/')
cd('/JMSSystemResources/PubJMSSystemResource/SubDeployments/pubsub')
set('Targets',jarray.array([ObjectName('com.bea:Name=PublicationJMSServer,Type=JMSServer')],
ObjectName))
cd('/')
cd('/JMSSystemResources/PubJMSSystemResource/JMSResource/PubJMSSystemResource/ConnectionFactories/PubConnectionFactory/DefaultDeliveryParams/PubConnectionFactory')
set('DefaultTimeToLive','0')
cd('/JMSSystemResources/PubJMSSystemResource/JMSResource/PubJMSSystemResource/ConnectionFactories/PubConnectionFactory/TransactionParams/PubConnectionFactory')
cmo.setTransactionTimeout(3600)
cmo.setXAConnectionFactoryEnabled(true)
activate()

